#!/usr/bin/env python3
"""
PropEdge V1.0 — propedge_control.py
=====================================
Comprehensive system check. Run anytime. Share output for remote diagnostics.

Usage:
  python3 propedge_control.py           # full check
  python3 propedge_control.py --quick   # skip CSV row counts
"""
from __future__ import annotations
import sys, os, json, pickle, ast, subprocess, importlib.util, argparse, platform
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).parent.resolve()
HOME = Path.home()

# ─────────────────────────────────────────────────────────────────────────────
class R:
    checks: list[dict] = []
    @classmethod
    def ok(cls, s, m, d=""): cls.checks.append({"st":"OK",  "s":s,"m":m,"d":d})
    @classmethod
    def warn(cls, s, m, d=""): cls.checks.append({"st":"WARN","s":s,"m":m,"d":d})
    @classmethod
    def fail(cls, s, m, d=""): cls.checks.append({"st":"FAIL","s":s,"m":m,"d":d})
    @classmethod
    def info(cls, s, m, d=""): cls.checks.append({"st":"INFO","s":s,"m":m,"d":d})
    @classmethod
    def n_ok(cls):   return sum(1 for c in cls.checks if c["st"]=="OK")
    @classmethod
    def n_warn(cls): return sum(1 for c in cls.checks if c["st"]=="WARN")
    @classmethod
    def n_fail(cls): return sum(1 for c in cls.checks if c["st"]=="FAIL")

def mb(p): 
    try: return f"{p.stat().st_size/1048576:.1f} MB"
    except: return "?"
def age_h(p):
    try: return (datetime.now().timestamp()-p.stat().st_mtime)/3600
    except: return 9999.0
def csv_rows(p):
    try:
        with open(p,'rb') as f: return sum(1 for _ in f)-1
    except: return -1
def json_plays(p):
    try:
        with open(p) as f: plays=json.load(f)
        w=sum(1 for x in plays if x.get("result")=="WIN")
        l=sum(1 for x in plays if x.get("result")=="LOSS")
        # Check if plays were generated by V1.0 (vs copied from V16)
        v1_count=sum(1 for x in plays if x.get("version","") in ("V1.0","") or True)
        return len(plays),w,l
    except: return -1,0,0


# ─────────────────────────────────────────────────────────────────────────────
# 1. SYSTEM
# ─────────────────────────────────────────────────────────────────────────────
def check_system():
    R.info("SYSTEM", f"Python {sys.version.split()[0]} | {platform.system()} {platform.machine()}")
    R.info("SYSTEM", f"Working dir: {ROOT}")
    R.info("SYSTEM", f"Run at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    needed = [("xgboost","xgboost"),("lightgbm","lightgbm"),("sklearn","scikit-learn"),
              ("pandas","pandas"),("numpy","numpy"),("openpyxl","openpyxl"),
              ("nba_api","nba_api"),("requests","requests"),("keyring","keyring")]
    missing=[pkg for mod,pkg in needed if not importlib.util.find_spec(mod)]
    if missing: R.fail("SYSTEM",f"Missing packages: {', '.join(missing)}",f"pip3 install {' '.join(missing)}")
    else:       R.ok("SYSTEM","All required packages installed")


# ─────────────────────────────────────────────────────────────────────────────
# 2. CONFIG
# ─────────────────────────────────────────────────────────────────────────────
def check_config():
    cfg_path = ROOT/"config.py"
    if not cfg_path.exists(): R.fail("CONFIG","config.py MISSING"); return
    try:
        ast.parse(cfg_path.read_text(encoding='utf-8'))
    except SyntaxError as e:
        R.fail("CONFIG",f"config.py syntax error: {e}"); return
    sys.path.insert(0,str(ROOT))
    try:
        spec=importlib.util.spec_from_file_location("config_v1",cfg_path)
        cfg=importlib.util.module_from_spec(spec); spec.loader.exec_module(cfg)
    except Exception as e:
        R.fail("CONFIG",f"config.py import error: {e}"); return

    # VERSION
    ver=getattr(cfg,"VERSION","?")
    if ver=="V1.0": R.ok("CONFIG",f"VERSION = {ver}")
    else: R.fail("CONFIG",f"VERSION = {ver}  (expected V1.0)","Run: python3 setup_v1.py")

    # GIT_REMOTE — accept both SSH and HTTPS
    gr=getattr(cfg,"GIT_REMOTE","?")
    ssh  = "git@github.com:iamwerewolf1007/PropEdgeV1.0.git"
    https= "https://github.com/iamwerewolf1007/PropEdgeV1.0.git"
    if gr in (ssh, https):
        R.ok("CONFIG",f"GIT_REMOTE = {gr}")
    else:
        R.warn("CONFIG",f"GIT_REMOTE = {gr}",
               f"Expected: {ssh} or {https}")

    # LOCAL_DIR — accept with or without hyphen (both valid)
    ld=getattr(cfg,"LOCAL_DIR",None)
    ok_local=[HOME/"Documents"/"GitHub"/"PropEdgeV1.0Local",
              HOME/"Documents"/"GitHub"/"PropEdgeV1.0-Local"]
    if ld in ok_local:
        R.ok("CONFIG",f"LOCAL_DIR = {ld}")
    else:
        R.warn("CONFIG",f"LOCAL_DIR = {ld}",
               f"Expected: {ok_local[0]}")

    # REPO_DIR
    rd=getattr(cfg,"REPO_DIR",None)
    exp_rd=HOME/"Documents"/"GitHub"/"PropEdgeV1.0"
    if rd==exp_rd: R.ok("CONFIG",f"REPO_DIR = {rd}")
    else: R.warn("CONFIG",f"REPO_DIR = {rd}",f"Expected: {exp_rd}")

    # V1 model path
    fv1=getattr(cfg,"FILE_V1_MODEL",None)
    if fv1:
        fn=Path(str(fv1)).name
        if "v1" in fn.lower(): R.ok("CONFIG",f"FILE_V1_MODEL → {fn}")
        else: R.warn("CONFIG",f"FILE_V1_MODEL → {fn}","Expected propedge_v1.pkl")

    # Feature counts
    ef=len(getattr(cfg,"ELITE_FEATURES",[]))
    nf=len(getattr(cfg,"V1_NEW_FEATURES",[]))
    vf=len(getattr(cfg,"V1_FEATURES",[]))
    R.info("CONFIG",f"ELITE_FEATURES={ef}, V1_NEW_FEATURES={nf}, V1_FEATURES={vf}")
    if nf==20 and ef==81 and vf==101:
        R.ok("CONFIG","Feature counts correct: 81 + 20 = 101")
    else:
        R.warn("CONFIG",f"Unexpected feature counts: {ef}+{nf}={vf} (expected 81+20=101)")

    # Tier thresholds
    t=getattr(cfg,"ELITE_THRESHOLDS",{})
    expected={"APEX":0.90,"ULTRA":0.85,"ELITE":0.78,"STRONG":0.72,"PLAY+":0.65}
    if t==expected:
        R.ok("CONFIG","Tier thresholds: APEX=0.90 ULTRA=0.85 ELITE=0.78 STRONG=0.72 PLAY+=0.65")
    else:
        R.warn("CONFIG",f"Tier thresholds: {t}","Expected V1.0 calibrated thresholds")


# ─────────────────────────────────────────────────────────────────────────────
# 3. VERSION STRINGS
# ─────────────────────────────────────────────────────────────────────────────
def check_version_strings():
    stale=["V16.0","V17.0","PropEdgeV16.0","PropEdgeV17.0",
           "v17_","V17_","build_v17","FILE_V17",
           "propedge_v17.pkl","propedge_elite_v2.pkl"]
    skip={"setup_v1.py","propedge_control.py"}
    offenders=[]
    for path in sorted(ROOT.rglob("*")):
        if not path.is_file(): continue
        if path.suffix not in {'.py','.html','.md','.txt'}: continue
        if path.name in skip: continue
        if any(p.startswith('.') for p in path.parts): continue
        if '__pycache__' in str(path): continue
        try: text=path.read_text(encoding='utf-8',errors='replace')
        except: continue
        found=[s for s in stale if s in text]
        if found: offenders.append((path.relative_to(ROOT),found))
    if offenders:
        for rel,pats in offenders[:8]:
            R.fail("VERSIONS",f"{rel}: {pats}","Run: python3 setup_v1.py")
        if len(offenders)>8:
            R.fail("VERSIONS",f"...and {len(offenders)-8} more files")
    else:
        R.ok("VERSIONS","All files reference V1.0 — no stale version strings")


# ─────────────────────────────────────────────────────────────────────────────
# 4. SYNTAX
# ─────────────────────────────────────────────────────────────────────────────
def check_syntax():
    py_files=sorted(ROOT.glob("*.py"))
    errors=[]
    for p in py_files:
        try: ast.parse(p.read_text(encoding='utf-8',errors='replace'))
        except SyntaxError as e: errors.append((p.name,str(e)))
    if errors:
        for n,e in errors: R.fail("SYNTAX",f"{n}: {e}")
    else:
        R.ok("SYNTAX",f"All {len(py_files)} .py files parse cleanly")


# ─────────────────────────────────────────────────────────────────────────────
# 5. SOURCE FILES
# ─────────────────────────────────────────────────────────────────────────────
def check_source_files(quick):
    src=ROOT/"source-files"
    if not src.exists(): R.fail("SOURCE FILES","source-files/ directory missing"); return
    files=[
        ("nba_gamelogs_2024_25.csv",                          5_000_000, True),
        ("nba_gamelogs_2025_26.csv",                          5_000_000, True),
        ("h2h_database.csv",                                  100_000,   True),
        ("PropEdge_-_Match_and_Player_Prop_lines_.xlsx",      100_000,   True),
        ("PropEdge_2024_25_Match_and_Player_Prop_lines.xlsx", 100_000,   False),
    ]
    for fname,min_size,required in files:
        p=src/fname
        if not p.exists():
            if required: R.fail("SOURCE FILES",f"{fname} MISSING",
                                f"Copy from V16.0-Local/source-files/{fname}")
            else: R.warn("SOURCE FILES",f"{fname} not present (optional)")
            continue
        size=p.stat().st_size
        if size<min_size: R.warn("SOURCE FILES",f"{fname}  {mb(p)}  (suspiciously small)"); continue
        detail=mb(p)
        if not quick and fname.endswith('.csv'):
            rows=csv_rows(p); detail=f"{mb(p)}, {rows:,} rows"
        R.ok("SOURCE FILES",f"{fname}  {detail}")


# ─────────────────────────────────────────────────────────────────────────────
# 6. MODELS
# ─────────────────────────────────────────────────────────────────────────────
def check_model_files():
    models=[
        ("V9.2/projection_model.pkl",     True,  "sub-model"),
        ("V10/projection_model.pkl",      True,  "sub-model"),
        ("V11/projection_model.pkl",      True,  "sub-model"),
        ("V12/projection_model.pkl",      True,  "sub-model"),
        ("V12/direction_classifier.pkl",  True,  "sub-model"),
        ("V12/calibrator.pkl",            True,  "sub-model"),
        ("V12/segment_model.pkl",         True,  "sub-model"),
        ("V12/quantile_models.pkl",       True,  "sub-model"),
        ("V12/player_trust.json",         False, "generated by: python3 run.py generate"),
        ("V14/projection_model.pkl",      True,  "sub-model"),
        ("V14/direction_classifier.pkl",  True,  "sub-model"),
        ("V14/calibrator.pkl",            True,  "sub-model"),
        ("V14/player_trust.json",         False, "generated by: python3 run.py generate"),
        ("elite/propedge_v1.pkl",         False, "PRIMARY — run: python3 run.py generate"),
        ("elite/propedge_v1_legacy.pkl",  False, "legacy fallback (optional)"),
    ]
    for rel,required,note in models:
        p=ROOT/"models"/rel
        if p.exists():
            if p.suffix=='.pkl':
                try:
                    with open(p,'rb') as f: obj=pickle.load(f)
                    extra=""
                    if isinstance(obj,dict):
                        keys=list(obj.keys())[:4]
                        extra=f"  keys:{keys}"
                    R.ok("MODELS",f"{rel}  {mb(p)}{extra}")
                except Exception as e:
                    R.fail("MODELS",f"{rel}  CORRUPT: {e}")
            else:
                R.ok("MODELS",f"{rel}  {mb(p)}")
        else:
            if required: R.fail("MODELS",f"{rel} MISSING",f"Copy from V16.0-Local/models/{rel}")
            else:        R.warn("MODELS",f"{rel} not present — {note}")

    # Check V1.0 model bundle keys
    v1_pkl = ROOT/"models"/"elite"/"propedge_v1.pkl"
    if v1_pkl.exists():
        try:
            with open(v1_pkl,'rb') as f: bundle=pickle.load(f)
            expected_keys={'xgb','lgb','lr','scaler','features','version','target'}
            missing_keys=expected_keys-set(bundle.keys())
            if missing_keys:
                R.warn("MODELS",f"propedge_v1.pkl missing bundle keys: {missing_keys}")
            else:
                n_plays=bundle.get('n_plays',0)
                target=bundle.get('target','?')
                n_feats=len(bundle.get('features',[]))
                trained=bundle.get('trained_at','?')[:19]
                R.ok("MODELS",
                     f"V1.0 bundle: {n_feats} features | target={target} | "
                     f"n={n_plays:,} plays | trained {trained}")
                # Critical check: was it trained on bet_win (direction-correct)?
                if target != 'bet_win':
                    R.warn("MODELS",
                           f"V1.0 model target='{target}' — expected 'bet_win'",
                           "Retrain with: python3 run.py generate (or retrain)")
        except Exception as e:
            R.warn("MODELS",f"Could not inspect propedge_v1.pkl: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# 7. DATA FILES
# ─────────────────────────────────────────────────────────────────────────────
def check_data_files():
    data=ROOT/"data"
    if not data.exists():
        R.warn("DATA","data/ missing — run: python3 run.py generate"); return

    for fname,label in [("season_2025_26.json","2025-26"),("season_2024_25.json","2024-25")]:
        p=data/fname
        if p.exists():
            total,wins,losses=json_plays(p)
            graded=wins+losses
            a=age_h(p)
            if total<0: R.fail("DATA",f"{fname} CORRUPT")
            else:
                # Check if data looks fresh (reasonable size) and has graded plays
                age_str=f"{a:.0f}h ago" if a<9000 else "age unknown"
                bet_win_rate=wins/(graded) if graded>0 else 0
                if graded<1000:
                    R.warn("DATA",f"{fname} {total:,} plays | {graded:,} graded | {age_str}",
                           "Very few graded plays — run: python3 run.py generate")
                else:
                    R.ok("DATA",
                         f"{fname}  {total:,} plays | {graded:,} graded "
                         f"({wins}W/{losses}L | WIN%={bet_win_rate:.1%}) | {age_str}")
                # Warn if WIN rate looks backwards (would indicate grading issue)
                if 0.3 < bet_win_rate < 0.5:
                    R.warn("DATA",
                           f"{fname} WIN rate={bet_win_rate:.1%} — this is the RAW WIN rate, "
                           f"not the BET WIN rate",
                           "BET WIN rate should be ~58-63%. Raw WIN rate of 46% is normal for OVER-only grading.")
        else:
            R.warn("DATA",f"{fname} not present",
                   "Run: python3 run.py generate")

    for fname,desc in [
        ("today.json",               "populated by predict batches"),
        ("dvp_rankings.json",        "auto-built on first predict"),
        ("propedge_ml_dataset.xlsx", "generated by: python3 run.py generate"),
        ("audit_log.csv",            "populated by grading batches"),
    ]:
        p=data/fname
        if p.exists():
            a=age_h(p)
            R.ok("DATA",f"{fname}  {mb(p)}  ({a:.0f}h ago)" if a<9000 else f"{fname}  {mb(p)}")
        else:
            R.warn("DATA",f"{fname} not present ({desc})")


# ─────────────────────────────────────────────────────────────────────────────
# 8. PREDICTION ENGINE — end-to-end accuracy check
# ─────────────────────────────────────────────────────────────────────────────
def check_accuracy():
    """
    Read season JSONs and compute actual prediction accuracy.
    This is the key metric: did V1.0 predict correctly?
    BET WIN = direction was correct (not just raw WIN).
    """
    data=ROOT/"data"
    all_plays=[]
    for fname in ("season_2024_25.json","season_2025_26.json"):
        p=data/fname
        if not p.exists(): continue
        try:
            with open(p) as f: plays=json.load(f)
            all_plays.extend(plays)
        except: pass

    if not all_plays:
        R.warn("ACCURACY","No season JSON data found — run: python3 run.py generate")
        return

    # Filter to graded plays only
    graded=[p for p in all_plays if p.get("result") in ("WIN","LOSS")]
    if not graded:
        R.warn("ACCURACY","No graded plays found in season JSONs")
        return

    # Compute BET WIN correctly
    def is_bet_win(p):
        direction=str(p.get("direction",p.get("dir","OVER"))or"OVER").upper()
        result=str(p.get("result",""))
        return result=="LOSS" if "UNDER" in direction else result=="WIN"

    bet_wins=[p for p in graded if is_bet_win(p)]
    baseline=len(bet_wins)/len(graded)

    R.info("ACCURACY",
           f"Total graded plays: {len(graded):,} | Baseline BET WIN rate: {baseline:.1%}")

    # Tier breakdown using stored elite_prob
    tiers=[
        ("APEX",   0.90, "≥0.90"),
        ("ULTRA",  0.85, "≥0.85"),
        ("ELITE",  0.78, "≥0.78"),
        ("STRONG", 0.72, "≥0.72"),
        ("PLAY+",  0.65, "≥0.65"),
    ]
    targets={"APEX":0.95,"ULTRA":0.90,"ELITE":0.85,"STRONG":0.80,"PLAY+":0.75}

    any_tier_data=False
    for tier_name,thresh,label in tiers:
        tier_plays=[p for p in graded
                    if float(p.get("elite_prob",p.get("conf",0)))>=thresh]
        if len(tier_plays)<5: continue
        any_tier_data=True
        tier_wins=[p for p in tier_plays if is_bet_win(p)]
        hr=len(tier_wins)/len(tier_plays)
        target=targets[tier_name]
        msg=f"{tier_name} ({label}): {hr:.1%} | n={len(tier_plays):,}"
        if hr>=target:
            R.ok("ACCURACY",msg,f"✓ target={target:.0%} MET")
        elif hr>=target-0.05:
            R.warn("ACCURACY",msg,f"⚠ target={target:.0%} CLOSE (within 5pp)")
        else:
            R.warn("ACCURACY",msg,f"✗ target={target:.0%} NOT YET MET — need more graded data")

    if not any_tier_data:
        R.warn("ACCURACY","Insufficient plays in confidence tiers — need more graded data",
               "Run: python3 run.py generate to score and grade all plays")

    # Sanity: check grading direction
    raw_wins=[p for p in graded if p.get("result")=="WIN"]
    raw_win_rate=len(raw_wins)/len(graded)
    if abs(raw_win_rate-0.465)>0.05:
        R.warn("ACCURACY",
               f"Raw WIN rate={raw_win_rate:.1%} (unusual — expected ~46-48%)",
               "Grading might be direction-aware rather than OVER-only")
    else:
        R.ok("ACCURACY",
             f"Raw WIN rate={raw_win_rate:.1%} — consistent with OVER-only grading (46-48% expected)")


# ─────────────────────────────────────────────────────────────────────────────
# 9. IMPORTS
# ─────────────────────────────────────────────────────────────────────────────
def check_imports():
    sys.path.insert(0,str(ROOT))
    for mod in ["config","feature_engineering","rolling_engine",
                "reasoning_engine","player_name_aliases"]:
        p=ROOT/f"{mod}.py"
        if not p.exists(): R.fail("IMPORTS",f"{mod}.py not found"); continue
        try:
            spec=importlib.util.spec_from_file_location(f"{mod}_v1",p)
            m=importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
            R.ok("IMPORTS",f"{mod}.py imports OK")
        except Exception as e:
            err=str(e)
            if "No module named" in err: R.fail("IMPORTS",f"{mod}.py: {err}")
            else: R.warn("IMPORTS",f"{mod}.py: {err[:80]}")


# ─────────────────────────────────────────────────────────────────────────────
# 10. SCHEDULER
# ─────────────────────────────────────────────────────────────────────────────
def check_scheduler():
    if platform.system()!="Darwin":
        R.info("SCHEDULER","Not on macOS — launchd not applicable"); return
    labels=["com.propedge.v1.batch0","com.propedge.v1.batch1",
            "com.propedge.v1.batch2","com.propedge.v1.batch3",
            "com.propedge.v1.batch4","com.propedge.v1.batch5",
            "com.propedge.v1.daily"]
    la=HOME/"Library"/"LaunchAgents"
    installed=[l for l in labels if (la/f"{l}.plist").exists()]
    if len(installed)==len(labels):
        R.ok("SCHEDULER",f"All {len(labels)} V1.0 launchd agents installed")
    elif installed:
        R.warn("SCHEDULER",f"{len(installed)}/{len(labels)} V1.0 agents installed",
               "Run: python3 run.py install")
    else:
        R.warn("SCHEDULER","No V1.0 launchd agents installed",
               "Run: python3 run.py install")
    stale=[l for l in ["com.propedge.v16.batch0","com.propedge.v17.batch0"]
           if (la/f"{l}.plist").exists()]
    if stale:
        R.warn("SCHEDULER",f"Stale agents still installed: {stale}",
               "Run: python3 setup_v1.py  (auto-removes stale agents)")


# ─────────────────────────────────────────────────────────────────────────────
# 11. GIT
# ─────────────────────────────────────────────────────────────────────────────
def check_git():
    repo_dir=HOME/"Documents"/"GitHub"/"PropEdgeV1.0"
    if not repo_dir.exists():
        R.warn("GIT",f"PropEdgeV1.0 not found at {repo_dir}"); return
    if not (repo_dir/".git").exists():
        R.warn("GIT","PropEdgeV1.0 exists but is not a git repo"); return
    R.ok("GIT",f"Repo found: {repo_dir}")
    try:
        r=subprocess.run(["git","-C",str(repo_dir),"remote","get-url","origin"],
                         capture_output=True,text=True,timeout=5)
        remote=r.stdout.strip()
        valid=["git@github.com:iamwerewolf1007/PropEdgeV1.0.git",
               "https://github.com/iamwerewolf1007/PropEdgeV1.0.git"]
        if remote in valid:
            R.ok("GIT",f"Remote origin: {remote}")
        else:
            R.warn("GIT",f"Remote: {remote}",
                   f"Expected: {valid[0]} or {valid[1]}")
    except Exception as e:
        R.warn("GIT",f"Could not check remote: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# PRINT REPORT
# ─────────────────────────────────────────────────────────────────────────────
IC={"OK":"✓","WARN":"⚠","FAIL":"✗","INFO":"ℹ"}
CC={"OK":"\033[32m","WARN":"\033[33m","FAIL":"\033[31m","INFO":"\033[36m","R":"\033[0m"}

def fmt(st,m,d=""):
    c=CC.get(st,""); r=CC["R"]; ic=IC.get(st,"?")
    if sys.stdout.isatty():
        ln=f"  {c}{ic}{r} {m}"
        if d: ln+=f"\n      {c}→{r} {d}"
    else:
        ln=f"  {ic} {m}"
        if d: ln+=f"\n    → {d}"
    return ln

def print_report():
    print(f"\n{'═'*62}")
    print(f"  PropEdge V1.0 — Control Report")
    print(f"  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  |  {ROOT}")
    print(f"{'═'*62}")
    cur=None
    for c in R.checks:
        if c["s"]!=cur: cur=c["s"]; print(f"\n[{cur}]")
        print(fmt(c["st"],c["m"],c.get("d","")))
    total=len([c for c in R.checks if c["st"]!="INFO"])
    print(f"\n{'─'*62}")
    print(f"  SUMMARY: {R.n_ok()}/{total} checks passed | "
          f"{R.n_warn()} warnings | {R.n_fail()} failures")
    if R.n_fail()==0 and R.n_warn()==0:
        print(f"\n  ✓ All checks passed — system is ready.")
    elif R.n_fail()==0:
        print(f"\n  ⚠ {R.n_warn()} warning(s) — system functional, review above.")
    else:
        print(f"\n  ✗ {R.n_fail()} failure(s) — action required.")

    # Action list
    actions=list(dict.fromkeys(
        c["d"] for c in R.checks if c["st"]=="FAIL" and c.get("d")
    ))
    if actions:
        print(f"\n  REQUIRED ACTIONS:")
        for a in actions[:5]: print(f"    • {a}")
    print(f"\n{'═'*62}\n")


# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────
def main():
    parser=argparse.ArgumentParser()
    parser.add_argument("--quick",action="store_true")
    args=parser.parse_args()
    check_system()
    check_config()
    check_version_strings()
    check_syntax()
    check_source_files(args.quick)
    check_model_files()
    check_data_files()
    check_accuracy()
    check_imports()
    check_scheduler()
    check_git()
    print_report()
    sys.exit(1 if R.n_fail()>0 else 0)

if __name__=="__main__":
    main()
